version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres